### ISSUE TITLE
ImportError: No module named inspector

### ISSUE THREAD

**Issue by 0xlen** [cb109/pyplantuml#2]
Hello,

You may occur the error something like this:
```
from asteroid.inspector import Linker ImportError: No module named inspector
```

Seems astroid.inspector is deprecated and integrated to pylint, so you may have to install astroid-1.4.9 to satisfy the dependancies.

### My installation steps:
```bash
# Install astroid-1.4.9
cd ~
git clone https://github.com/PyCQA/astroid
cd astroid/
git checkout astroid-1.4.9
python setup.py install

# Install pylint
cd ~
git clone https://github.com/PyCQA/pylint
python setup.py install

# Download plantuml and move to /usr/bin
cd ~
wget https://nchc.dl.sourceforge.net/project/plantuml/plantuml.jar
mv plantuml.jar /usr/bin

# Install pyplantuml
pip install pyplantuml
```

**[Pyreverse since September 2008, it has been integrated with Pylint](https://www.logilab.org/blogentry/6883). You may not need to install the Pyreverse in this step.**

For more information, you can also check out this information below:
```
    * astroid.inspector was moved to pylint.pyreverse, since
      it is the only known client of this module. No other change
      was made to the exported API.
```
- [astroid ChangeLog](https://github.com/PyCQA/astroid/blob/master/ChangeLog)

I hope this information will be helpful to you as well.

**Comment by cb109** [comment]
Thanks a lot for reporting and the detailled steps! I might pick up this project again one day, and being stuck on this very old astroid version is the largest problem right now that will then have to be tackled.

**Comment by 0xlen** [comment]
Hi @cb109,

Thanks for your care and reply.

It is really AWESOME and saving my time to graph the diagram very well. I will keep following on this project. Looking forward to your picking up this soon.

**Comment by VictorUceda** [comment]
I've this problem too. There is any solution for this issue? 

I can parse any class of my python3 project with the original packet versions (astroid==1.3.2, pylint==1.4)

Thanks in advance!

**Comment by cb109** [comment]
@VictorUceda I was able to install this package and run the commandlinetool to produce PNGs successfully using Python 2.7.15, without any extra downgrading of packages. I could however not make this work with Python 3.7, after downgrading pylint and astroid to the versions you mentioned it still failed with: `AttributeError: 'Call' object has no attribute 'starargs'`.

I haven't used this package in a long time and will likely not find the motivation to fix this stuff, sorry. I'll review and merge any helpful PR though.

**Comment by VictorUceda** [comment]
Yes, I'm using python 3.7 and I found that error. I've tried differents version of the packages but differents problems persist.

Thanks any way!
If I find time I will try to find a solution, in that case I launch a PR.
